import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("sign-in/*", "routes/sign-in.tsx"),
  route("sign-up/*", "routes/sign-up.tsx"),
  route("account-pending", "routes/account-pending.tsx"),
  route("user-not-found", "routes/user-not-found.tsx"),
  route("dev-login", "routes/dev-login.tsx"),
  route("pricing", "routes/pricing.tsx"),
  route("success", "routes/success.tsx"),
  route("subscription-required", "routes/subscription-required.tsx"),
  route("admin", "routes/admin.tsx"),
  route("admin/grant-me", "routes/admin.grant-me.tsx"),
  route("admin/setup", "routes/admin/setup.tsx"),
  route("admin/quick-access", "routes/admin/quick-access.tsx"),
  layout("routes/dashboard/layout.tsx", [
    route("dashboard", "routes/dashboard/index.tsx"),
    route("upload", "routes/upload.tsx"),
    route("sales", "routes/sales.tsx"),
    route("inventory", "routes/inventory.tsx"),
    route("budget", "routes/budget.tsx"),
    route("settings", "routes/settings.tsx"),
    route("chat", "routes/chat.tsx"),
  ]),
  layout("routes/store-ops/layout.tsx", [
    route("store-ops", "routes/store-ops/index.tsx"),
    route("store-ops/operational", "routes/store-ops/operational.tsx"),
    route("store-ops/averages", "routes/store-ops/averages.tsx"),
    route("store-ops/daily-checklist", "routes/store-ops/daily-checklist.tsx"),
    route("store-ops/sl-checklist", "routes/store-ops/sl-checklist.tsx"),
    route("store-ops/dl-checklist", "routes/store-ops/dl-checklist.tsx"),
    route("store-ops/returns", "routes/store-ops/returns.tsx"),
    route("store-ops/callbacks", "routes/store-ops/callbacks.tsx"),
    route("store-ops/close-dated", "routes/store-ops/close-dated.tsx"),
    route("store-ops/tablet-counts", "routes/store-ops/tablet-counts.tsx"),
    route("store-ops/cleaning", "routes/store-ops/cleaning.tsx"),
    route("store-ops/budget", "routes/store-ops/budget.tsx"),
    route("store-ops/notifications", "routes/store-ops/notifications.tsx"),
    route("store-ops/settings", "routes/store-ops/settings.tsx"),
  ]),
] satisfies RouteConfig;
